#!/bin/bash
repositorypath=pa-art.liveaction.com/artifactory/app-snapshot-local/com/liveaction/LiveActionClient/$1/$2/
repositoryurl = https://pa-art.liveaction.com/artifactory/app-snapshot-local/com/liveaction/LiveActionClient/$1/$2/
wget -r -np $repositorypath

