#!bin/bash
readarray -t Array1 <<<  "$(for i in $repository/$2/* ; do md5sum $i ; done )"

aws s3 cp $repository/$2  s3://devopsnxt/$1/  --recursive --exclude "premd5sum.out"

aws s3 cp s3://devopsnxt/test  s3downlaod/  --recursive\

readarray -t Array2 <<< "$(for i in s3downlaod/* ; do md5sum $i ; done )"

echo ${Array1[@]} ${Array2[@]} | tr ' ' '\n' | sort | uniq -u


